### ISSUE TITLE
Import install guides from TEO_Network_information

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/installation-guides#11]
From wiki http://robots.uc3m.es/index.php/TEO_Network_information
- [x] Netgear A6100 WiFi USB Mini Adapter
- [x] JR3 card

**Comment by rsantos88** [comment]
done it #27

**Comment by jgvictores** [comment]
@rsantos88 Looks great!

**Comment by jgvictores** [comment]
PS: Will start doing some minor improvements on it, but very happy with this step!
