### ISSUE TITLE
Import install guides from yarp-devices

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/installation-guides#12]
From https://github.com/roboticslab-uc3m/yarp-devices
- [x] https://github.com/roboticslab-uc3m/yarp-devices/blob/bc56a3e/doc/yarp-devices-install-hcanpci-on-debian-6.md

**Comment by rsantos88** [comment]
do you want to move it? (deleting `yarp-devices-install-hcanpci-on-debian-6.md` from `yarp-devices`)

**Comment by jgvictores** [comment]
Yes, import as in "move" (copy, update format, delete originql) and update pages that pointed to it.

**Comment by PeterBowman** [comment]
Fixed link in description, now pointing at current HEAD.

**Comment by rsantos88** [comment]
done [here](https://github.com/roboticslab-uc3m/yarp-devices/pull/151)

**Comment by jgvictores** [comment]
Was added to this repository at a0e2da5. @rsantos88 thanks!
