### ISSUE TITLE
Update CMake installation guide

### ISSUE THREAD

**Issue by Kuronogard** [roboticslab-uc3m/installation-guides#19]
In the current master of YARP, CMake3.0 is a dependency, while Ubuntu 14.04 installs CMake 2.8 by default. Because of that, i think we should include the backport installation in the CMake guide
```bash
sudo apt-get install cmake3 cmake3-curses-gui
```
Also, there are references in the guide to ubuntu 12.04, are they still needed?

**Comment by jgvictores** [comment]
I'd add a Ubuntu 14.04 section right above the 12.04 one, and live with the 12.04 section for now.

**Comment by jgvictores** [comment]
https://github.com/roboticslab-uc3m/installation-guides/commit/11290508ad027bbf96ea2ca8dc507d8eab9d0cc6
