### ISSUE TITLE
Problems intalling PCL ubuntu 14.04 (Trusty) 

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/installation-guides#2]
Hi again!

I had some problems installing PCL in ubuntu 14.04 following the installation [guide](https://github.com/roboticslab-uc3m/installation-guides/blob/develop/install_pcl.md). The "libpcl-dev" and "pcl-tools" were not found in the repositories.

To solve this i followed the pcl installation instruction from the official [page](http://www.pointclouds.org/downloads/linux.html). This means:
```bash
sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
sudo apt-get update
sudo apt-get install libpcl-all
```

Maybe, if in the other versions of ubuntu works the current guide, could be interesting to add this instructions for ubuntu 14.04.

**Comment by jgvictores** [comment]
I've updated the installation [guide](https://github.com/roboticslab-uc3m/installation-guides/blob/develop/install_pcl.md) based on previous info and directly browsing [the PPA](http://ppa.launchpad.net/v-launchpad-jochen-sprickerhof-de/pcl/ubuntu/dists/).
