### ISSUE TITLE
qt versions

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/installation-guides#30]
_From @jgvictores on December 14, 2017 21:4_

- openrave: qt4
- yarp: qt5

Makes sense?

_Copied from original issue: roboticslab-uc3m/openrave-yarp-plugins#52_

**Comment by PeterBowman** [comment]
Why not? Looks like OR isn't prepared yet for a major upgrade and is still stuck at Qt4, but both libraries may coexist on the same system (at least shared libraries changed their name, see [libqtcore4](https://packages.ubuntu.com/xenial/amd64/libqtcore4/filelist) vs [libqt5core5a](https://packages.ubuntu.com/xenial/amd64/libqt5core5a/filelist)).

**Comment by jgvictores** [comment]
Ok, I wanted to have a second opinion. Thanks a lot, closing!
