### ISSUE TITLE
Document yarp-python bindings

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/installation-guides#6]
Yarp-python binding installation should be documented in the yarp installation [guide](https://github.com/roboticslab-uc3m/installation-guides/blob/develop/install_yarp.md). @jgvictores  can you help with this?

**Comment by jgvictores** [comment]
Related: https://github.com/roboticslab-uc3m/speech/issues/11

**Comment by jgvictores** [comment]
Note: For Trusty, recommend swig 3.0, see https://github.com/roboticslab-uc3m/installation-guides/issues/18#issuecomment-328294873
