### ISSUE TITLE
[keras] Add how to install keras

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/installation-guides#68]
Should we add an installation guide for Keras?

Right now i am referencing the official [site](https://keras.io/#installation).

**Comment by jgvictores** [comment]
PR is welcome!

**Comment by RaulFdzbis** [comment]
I don't any idea about what PR means :D

**Comment by jgvictores** [comment]
Public relations (PR) is the way organisations, companies and individuals communicate with the public and media. But in GitHub, it's Pull Request! :smiley:

**Comment by RaulFdzbis** [comment]
ohh yes... that makes sense hahahhahaha

**Comment by jgvictores** [comment]
Closing as now keras is integrated in tensorflow2.
