### ISSUE TITLE
[tensorflow_cc] error loading shared libraries

### ISSUE THREAD

**Issue by davidvelascogarcia** [roboticslab-uc3m/installation-guides#70]
If you try to install programs that use `tensorflow_cc` shared libraries, the next error will appear after execute your program.

```bash
error while loading shared libraries: libtensorflow_cc.so: cannot open shared object file: No such file or directory
```

Fix by @jgvictores.

```bash
sudo ln -s /usr/local/lib/tensorflow_cc/libtensorflow_cc.so /usr/local/lib/libtensorflow_cc.so
sudo ldconfig
```

**Comment by PeterBowman** [comment]
That's https://github.com/FloopCZ/tensorflow_cc/issues/184. Fixed in tensorflow_cc v1.15.0 via https://github.com/FloopCZ/tensorflow_cc/commit/8019a9b604549e5978f5640579b83cc4054943e8.
