### ISSUE TITLE
Document installation of PCan

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/installation-guides#71]
Web: https://www.peak-system.com/fileadmin/media/linux/index.htm.

User manual: [PCAN-Driver-Linux_UserMan_eng.pdf](https://github.com/roboticslab-uc3m/installation-guides/files/3339541/PCAN-Driver-Linux_UserMan_eng.pdf)

To be linked from [specific-dependencies.csv](https://github.com/roboticslab-uc3m/yarp-devices/blob/fc417a504e1143f5f65e3e4d36027105fc2021a6/doc/specific-dependencies.csv). BTW also check [os-requirements.csv](https://github.com/roboticslab-uc3m/yarp-devices/blob/fc417a504e1143f5f65e3e4d36027105fc2021a6/doc/os-requirements.csv).

**Comment by rsantos88** [comment]
If you want, I can document it with the steps I followed yesterday for the installation in the manipulation :point_up:

**Comment by PeterBowman** [comment]
> If you want, I can document it with the steps I followed yesterday for the installation in the manipulation point_up

Sure, that would be great, thanks!

**Comment by rsantos88** [comment]
https://github.com/roboticslab-uc3m/installation-guides/pull/72

**Comment by rsantos88** [comment]
now it's ready to merge #72

**Comment by PeterBowman** [comment]
Closed in https://github.com/roboticslab-uc3m/installation-guides/pull/72, thanks!
