### ISSUE TITLE
[cmake] update requirement and guides

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/installation-guides#75]
- https://github.com/robotology/QA/issues/364
- https://askubuntu.com/questions/952429/is-there-a-good-ppa-for-cmake-backports
- https://github.com/roboticslab-uc3m/questions-and-answers/issues/84#issuecomment-559400444

**Comment by PeterBowman** [comment]
Preferred way: use Kitware's PPA ([answer](https://askubuntu.com/a/1138455)). We are not going to support Ubuntu Trusty (14.04) anymore (concerning [this answer](https://askubuntu.com/a/953211)).
