### ISSUE TITLE
[gazebo] Using Gazebo in virtual machine

### ISSUE THREAD

**Issue by davidvelascogarcia** [roboticslab-uc3m/installation-guides#80]
## Using Gazebo in virtual machine

Some errors appear if you try to use `Gazebo` in virtual machine like `VMware` or `Virtual Box` with o.s `Ubuntu Xenial 16.04`.

Some errors like:
- `Gazebo` crash and close instantly.
Can be solved with:
```bash
export SVGA_VGPU10=0
echo "export SVGA_VGPU10=0" >> ~/.profile
```
- `Gazebo` init load models and close immediately.

If you install `Gazebo` with `ROS Kinetic` the version that install is `7.0.0`.
This problem was solved on `7.4.0` version. 
Can be solved installing last `Gazebo 7` release:
```bash
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
sudo apt-get update
sudo apt-get install gazebo7 -y
```

## Related links
-[Gazebo init load and close VM](https://github.com/uzh-rpg/rpg_quadrotor_control/issues/58)
-[Gazebo crash VM](https://answers.gazebosim.org//question/13214/virtual-machine-not-launching-gazebo/)

**Comment by PeterBowman** [comment]
Ubuntu 16.04 (Xenial) has no official support anymore due to its LTS expiry. Starting from Ubuntu 18.04 (Bionic), Gazebo 9 or newer should be targeted (actually migrating to Gazebo 11 at time of writing due to a dependency on robotology code).
