### ISSUE TITLE
OpenGL error detected on modern OpenRAVE installations

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/installation-guides#83]
I've installed Openrave on Ubuntu Focal Fossa distribution following the instructions documented in [install-openrave-0540-ubuntu-2004-focal](https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-openrave.md#install-openrave-0540-ubuntu-2004-focal) + [teo-openrave-models](https://github.com/roboticslab-uc3m/teo-openrave-models/blob/master/doc/teo-openrave-models-install.md#install-the-models) + [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/blob/master/doc/openrave-yarp-plugins-install.md#install-openrave-yarp-plugins-on-ubuntu-working-on-all-tested-versions) + [Boost](https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-boost.md#install-boost-ubuntu) and it apparently works but the following errors are displayed in the terminal:

![image](https://user-images.githubusercontent.com/15872457/118690917-d2c05000-b808-11eb-8b18-59f3863bd989.png)
[teoSim-terminal.txt](https://github.com/roboticslab-uc3m/installation-guides/files/6502935/teoSim-terminal.txt)

**Comment by PeterBowman** [comment]
Those are warnings. Do they prevent teoSim from running for you? I'm already used to them, they're just bloating the terminal, everything works fine.

**Comment by rsantos88** [comment]
Perfect. If all this is normal, I close the issue.
Thanks!
